#!/usr/bin/env python3
# Copyright (c) 2026 UniVex Studios. All Rights Reserved.
"""Byte-embeds a binary file as a C++20 `inline constexpr std::array<std::uint8_t, N>` .inc,
byte-for-byte compatible with this repo's established embedded-asset convention (16 uppercase
hex bytes per line, 4-space indent, trailing comma on every entry - the same layout the
previously hand-committed font .inc files used; those are now generated at build time from a
single canonical source instead).

Usage:
    embed_file.py <input> <output.inc> <symbol_name> [--comment="free text"]

Example (from Engine/Runtime/UI/CMakeLists.txt):
    embed_file.py assets/fonts/liberation-sans-subset.ttf \
        ${CMAKE_CURRENT_BINARY_DIR}/generated/ui_font_ttf_bytes.inc \
        uve_ui_runtime_font_ttf_bytes
"""

import argparse
import sys
from pathlib import Path

BYTES_PER_LINE = 16


def render(data: bytes, symbol: str, comments: list[str]) -> str:
    lines = ["// Copyright (c) 2026 UniVex Studios. All Rights Reserved.", "//"]
    lines.append("// Generated by Engine/Tools/embed_file.py at build time - do not edit by hand.")
    for comment in comments:
        lines.append(f"// {comment}")
    lines.append(f"inline constexpr std::array<std::uint8_t, {len(data)}> {symbol}{{{{")
    for offset in range(0, len(data), BYTES_PER_LINE):
        chunk = data[offset : offset + BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    lines.append("}};")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Embed a binary file as a C++ byte-array .inc")
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("symbol")
    parser.add_argument("--comment", action="append", default=[], help="extra comment line(s)")
    args = parser.parse_args()
    try:
        data = args.input.read_bytes()
    except OSError as error:
        print(f"embed_file.py: cannot read {args.input}: {error}", file=sys.stderr)
        return 1
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(data, args.symbol, args.comment), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
