#!/usr/bin/env python3
# Copyright (c) 2026 UniVex Studios. All Rights Reserved.
"""Embeds the editor's icon PNGs as one C++ table, at build time.

Each input is <icon_root>/<group>/<id>.png. The output .inc holds one byte array per icon and
kEditorIconSourcesUVE, a table of {group, id, bytes} sorted by group then id. It expects the
including file to have declared EditorIconSourceUVE and EditorIconGroupUVE
(Engine/Editor/EditorCore/Internal/editor_icon_set_uve.h).

Usage:
    embed_editor_icons.py <output.inc> <icon_root> <png>...
"""

import sys
from pathlib import Path

# Directory name -> EditorIconGroupUVE enumerator, in the enum's order.
GROUPS = {"nodes": "Node", "node_categories": "NodeCategory", "content_types": "ContentType"}
BYTES_PER_LINE = 16


def main():
    if len(sys.argv) < 4:
        print(__doc__, file=sys.stderr)
        return 2
    output, root = Path(sys.argv[1]), Path(sys.argv[2]).resolve()
    entries = []
    for argument in sys.argv[3:]:
        path = Path(argument).resolve()
        group = path.parent.name
        if path.parent.parent != root or group not in GROUPS or path.suffix != ".png":
            print(f"embed_editor_icons.py: {path} is not <icon_root>/<group>/<id>.png", file=sys.stderr)
            return 1
        entries.append((list(GROUPS).index(group), path.stem, path.read_bytes()))
    entries.sort(key=lambda entry: (entry[0], entry[1]))

    lines = ["// Copyright (c) 2026 UniVex Studios. All Rights Reserved.", "//",
             "// Generated by Engine/Tools/editor_icons/embed_editor_icons.py at build time - do not edit by hand."]
    for index, (_, _, data) in enumerate(entries):
        lines.append(f"inline constexpr std::array<std::uint8_t, {len(data)}> kEditorIconPng{index}UVE{{{{")
        for offset in range(0, len(data), BYTES_PER_LINE):
            lines.append("    " + ", ".join(f"0x{value:02X}" for value in data[offset:offset + BYTES_PER_LINE]) + ",")
        lines.append("}};")
    lines.append(f"inline constexpr std::array<EditorIconSourceUVE, {len(entries)}> kEditorIconSourcesUVE{{{{")
    for index, (group, name, _) in enumerate(entries):
        lines.append(f"    {{EditorIconGroupUVE::{list(GROUPS.values())[group]}, \"{name}\", kEditorIconPng{index}UVE}},")
    lines.append("}};")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
