// Copyright (c) 2026 UniVex Studios. All Rights Reserved.

#pragma once

#include <cstdint>
#include <span>
#include <string_view>
#include <vector>

namespace UVE::Editor {

/// The editor's built-in icon artwork, without any GL: what is embedded, how to find it, and how
/// one icon becomes the mip chain EditorUiAssetsUVE uploads. Kept free of GL so the tests can check
/// that every node type, palette category and content type has a picture that decodes.
///
/// The artwork is generated by Engine/Tools/editor_icons/ into assets/icons/<group>/<id>.svg and
/// .png, and the build embeds the PNGs. An icon's id is the name it is looked up by: a node's
/// registry typeId, a palette category, a content browser type label.

/// One directory under assets/icons/ each.
enum class EditorIconGroupUVE : std::uint8_t {
    Node,         // nodes/          - one per scene node type, by typeId ("box_mesh_3d")
    NodeCategory, // node_categories/ - one per node palette category ("physics")
    ContentType,  // content_types/  - one per content browser type ("mesh", "folder_open")
};

struct EditorIconSourceUVE final {
    EditorIconGroupUVE group = EditorIconGroupUVE::Node;
    std::string_view name;
    std::span<const std::uint8_t> png;
};

/// Every embedded icon, sorted by group and then name.
[[nodiscard]] std::span<const EditorIconSourceUVE> GetEditorIconSourcesUVE() noexcept;

/// The icon `name` in `group`, or null. Case-insensitive (ASCII), so a category's display name
/// ("Physics") and a content browser label ("Mesh") find their icon as they are.
[[nodiscard]] const EditorIconSourceUVE* FindEditorIconSourceUVE(EditorIconGroupUVE group,
                                                                 std::string_view name) noexcept;

/// One level of an icon's mip chain: a square of straight-alpha RGBA8 pixels.
struct EditorIconLevelUVE final {
    int size = 0;
    std::vector<std::uint8_t> rgba;
};

/// Decodes an icon PNG into its full mip chain, from the PNG's own size down to 1x1. Empty when the
/// bytes do not decode or the image is not a square power of two - a chain that stops short is
/// not a complete texture, and the icon would draw as nothing on some drivers.
[[nodiscard]] std::vector<EditorIconLevelUVE> DecodeEditorIconUVE(std::span<const std::uint8_t> png);

/// Halves a square straight-alpha RGBA8 image (size a power of two, at least 2) by averaging each
/// 2x2 block with colour weighted by alpha. A plain average would pull the transparent pixels'
/// black into every antialiased edge, so a small icon would grow a dark rim.
[[nodiscard]] std::vector<std::uint8_t> DownsampleEditorIconUVE(std::span<const std::uint8_t> rgba, int size);

} // namespace UVE::Editor
